[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@maverick=lib/maverick-protocol/contracts',
    '@layerzerolabs/=lib/',
    '@solmate=lib/solmate/src',
]

# eth_rpc_url = "http://127.0.0.1:8545"
optimizer = true
optimizer_runs = 1000000
fuzz_runs = 32768
solc_version = "0.8.21"
via_ir = true # TODO use for production
evm_version = 'paris'

[rpc_endpoints]
base = "${BASE_RPC_URL}"
bnb = "${BNB_RPC_URL}"

[etherscan]
base = { key = "${BASE_API_KEY}", url = "https://api.basescan.org/api" }
bnb = { key = "${BNB_API_KEY}", url = "https://api.bscscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
